### ISSUE TITLE
not working with have.attr when looking for a specific value

### ISSUE THREAD

**Issue by x9sim9** [bahmutov/cypress-if#111]
e.g.

.if('have.attr', 'attributeName', 'valueOfAttr')

throws a typescript error as not expecting the 3rd parameter and does not check check the valueOfAttr

**Comment by bahmutov** [comment]
<img width="755" alt="Screenshot 2024-10-15 at 9 48 54 AM" src="https://github.com/user-attachments/assets/1650ec1c-6a60-4b55-8900-257c97b726eb">
