### ISSUE TITLE
Getting error cy.currentSubject is not a function

### ISSUE THREAD

**Issue by shash-hegde** [bahmutov/cypress-if#21]
Getting error cy.currentSubject is not a function on using the cypress if plugin
Cypress Version: 9.6.0

Below is the sample code:

```
	cy.get('div[role="dialog"]')
			.if('visible')
			.then(() => {
				cy.log('closing the dialog');
				cy.contains('button', 'Close').click();
			})
			.else()
			.then(() => {
				cy.log('Already closed');
			});
```
![cypress if](https://user-images.githubusercontent.com/63699449/188149268-7df78b6d-513f-4304-ad45-2fa07dd424ac.png)

**Comment by bahmutov** [comment]
Yeah, this is Cypress v10 function. I am not sure if I want to maintain this plugin to be backwards compatible and work in Cypress v9. I will think about it, but if anyone wants to open a PR (has to be testing it too), that would be nice

**Comment by elainedcb** [comment]
I'm also getting this error in Cypress v10.2.0, is it only for higher v10 versions?

**Comment by bahmutov** [comment]
Could use v9 testing approach similar to https://github.com/bahmutov/cypress-wait-if-happens/pull/1
