### ISSUE TITLE
Cypress-if no longer working after upgrade to Cypress 12.0.1

### ISSUE THREAD

**Issue by borecz** [bahmutov/cypress-if#58]
<img width="599" alt="image" src="https://user-images.githubusercontent.com/57007154/206136544-a3bd3c9a-1f7f-4dc1-8b52-d6dba9db4b5e.png">

<img width="568" alt="image" src="https://user-images.githubusercontent.com/57007154/206136591-f999e6d3-69e1-4c87-83a4-769a9bc89b11.png">

# Gleb's update

Everyone, it is not up to me - Cypress internal command API has changed a lot and it is problematic for me to do the same functionality right now. I have played with newer Cypress versions trying to find a way to implement the same feature in the PR https://github.com/bahmutov/cypress-if/pull/62 but without any success. If anyone can achieve it and fix it, I will happily merge your PR and release the new version.

**Comment by obajaddi** [comment]
![image](https://user-images.githubusercontent.com/51787457/206162895-51a9a75a-39fb-4e3e-8e3e-c23f64a1d15c.png)

I haven't seen that before ? I'm interested Gleb how it can be fixed :) 

Thanks

**Comment by bahmutov** [comment]
Well, I will open an issue for Cypress team, it is weird not to allow overwriting commands like `cy.get`

**Comment by estefafdez** [comment]
Thanks for the quick 👀  if there's anything I can do to help please let me know :)

**Comment by estefafdez** [comment]
done @bahmutov ! I will let you know and also try to ask about it in the ambassador meeting today.

**Comment by estefafdez** [comment]
Any update on this problem @bahmutov? it still don't work with cypress 12.1.0

**Comment by bahmutov** [comment]
@estefafdez this is blocked by Cypress itself and can be fixed if the test runner allows https://github.com/cypress-io/cypress/issues/25078

**Comment by sumankMSI** [comment]
When does Cypress-if plugin will be compatible with Cypress version 12.0.1, I am not to update Cypress version to latest one.

**Comment by bahmutov** [comment]
@sumankMSI please see the blocking issue. I know it is frustrating, i cannot upgrade my projects to v12 to use cypress-map and cypress-if :( Either Cypress allows overwriting queries, or someone comes up with an alternative implementation for cypress-if and opens a pull request here, and I will quickly merge it if it works

**Comment by mjustin** [comment]
Looks like yesterday's [12.6.0](https://docs.cypress.io/guides/references/changelog#12-6-0) release of Cypress added the ability to override queries.

> It is now possible to overwrite query commands using [`Cypress.Commands.overwriteQuery`](https://on.cypress.io/api/custom-queries). Addressed in [#25078](https://github.com/cypress-io/cypress/issues/25078).

**Comment by darialuzan** [comment]
I am still experiencing this issue after upgrading to Cypress v12.6.0
![image](https://user-images.githubusercontent.com/91475803/219399048-ab752f35-ac20-4fad-87f7-6ceca045958d.png)
![image](https://user-images.githubusercontent.com/91475803/219399288-2ed65adc-f5cd-4116-aa45-98a8e4a08040.png)

**Comment by aleksandar-embroker** [comment]
Any news on this?

**Comment by bahmutov** [comment]
No progress, v12.6.0 added query overwrite but removed some other things so I still don’t understand how to change the behavior Sent from my iPhoneOn Feb 22, 2023, at 06:47, Aleksandar Veselinovic ***@***.***> wrote:﻿
Any news on this?

**Comment by aleksandar-embroker** [comment]
Thx for an answer @bahmutov , I appreciate it. Will keep watching on this issue

**Comment by Cookuricoo1** [comment]
Same here

**Comment by sumankMSI** [comment]
Cypress updates are available frequently but unfortunately major add-ons, not works(cypress-if). It is time to think that we will go for a new update or fix the bug. The fix is essential otherwise it might not possible to use the latest version.

**Comment by mateustalles** [comment]
Indeed, even with the latest version it still doesn't work.

**Comment by cmesav** [comment]
I have the same issue, cypress version v12.6.0.
any update??
![image](https://user-images.githubusercontent.com/76462142/224130966-abd20739-b3bb-4cf5-b859-5a43ce68a316.png)

**Comment by ktxxt** [comment]
@cmesav be patient bro, we're all waiting.

**Comment by estefafdez** [comment]
hey @bahmutov, how is this issue going? the new version (12.8.0) was just released today. Thanks!

**Comment by sumankMSI** [comment]
> hey @bahmutov, how is this issue going? the new version (12.8.0) was just released today. Thanks!

Same Cypress-if issue as previous.

**Comment by nikepol** [comment]
people, stop asking Gleb about the status, if you want to help - create a merge request, or look at the progress at Pull requests, while this issue is opened that means there is no fix yet

**Comment by Fruehwirth** [comment]
When will this be fixed?

**Comment by bahmutov** [comment]
@Fruehwirth it will be fixed when Cypress internal code supports it, so far I could not figure out a hack to make it work

**Comment by bogdan-lucaci** [comment]
Hope this helps someone 🙃 I really needed the conditional existence for my tests and the workaround suggested [here](https://glebbahmutov.com/blog/upgrade-cypress-v9-to-v12/) by using `.should(Cypress._.noop)` was breaking Cypress's retry mechanism, but this aproach, using [`MutationObserver`](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver) and a 2 Promises race worked for me:

```javascript
const _waitForElement = (document, CSSselector) => {
    const throwOnTimeout = new Promise((_, reject) =>
        setTimeout(() => {
            const _errMsg = `WARNING: Timeout - Optional element [ ${CSSselector} ] not present, continuing...`
            cy.log(_errMsg)
            reject(new Error(_errMsg))
        }, Cypress.config('defaultCommandTimeout'))
    )
    const getElement = new Promise(resolve => {
        if (document.querySelector(CSSselector)) {
            return resolve(document.querySelector(CSSselector))
        }

        const observer = new MutationObserver(mutations => {
            if (document.querySelector(CSSselector)) {
                resolve(document.querySelector(CSSselector))
                observer.disconnect()
            }
        })

        observer.observe(document.body, {
            childList: true,
            subtree: true
        })
    })

    return Promise.race([getElement, throwOnTimeout])
}
```

and consumed it like this:
```javascript
cy
  .document()
  .then($doc => {
      return _waitForElement($doc, CSSselector)
          .then(elem => elem)
          .catch(error => { console.log(error) })
  })
  .then(elem => {
      if (elem)
          // handle found element
  })
```

**Comment by mateustalles** [comment]
@bahmutov With Cypress v12.15.0  think all we need is to merge your PR now?! I just replaced the `overwrite` with `overwriteQuery` locally and it worked!
![image](https://github.com/bahmutov/cypress-if/assets/39180176/a4e2018b-b8b2-4869-a23b-54cc1560a6cb)
![image](https://github.com/bahmutov/cypress-if/assets/39180176/3e7a5d34-8714-4f29-a2ce-40731ec740c5)

**Comment by felixpro** [comment]
Hi Guys, in the mean time we can use this: 

I added this as a constant function. 

`export const optionalFindingElement = (element: string) => {
  return Cypress.$(element).length;
};
`

and then use it like this: 

`Given('There are not assets generated by cypress in the kanban', () => {
  const assetNumber = optionalFindingElement('[data-fx-name="assetName"]');
  if (assetNumber > 0) {
   // Do something if the element was found
  } else {
 // Do something if the element was not found
}
});
`

sheers!

**Comment by FMuellerBK** [comment]
Hey guys, here's a working typescript version for Angular 16.1.5 and Cypress 12.17.1:
`const isIfCommand = (cmd: any) => cmd && cmd.attributes && cmd.attributes.name === 'if';

const skipCommand = (cmd: any) => {
  cmd.attributes.skip = true;
  cmd.state = 'skipped';
};

function skipRestOfTheChain(cmd: any, chainerId: string) {
  while (cmd && cmd.attributes.chainerId === chainerId && cmd.attributes.name !== 'finally') {
    skipCommand(cmd);
    cmd = cmd.attributes.next;
  }
}

function findMyIfSubject(elseCommandAttributes: any): any {
  if (!elseCommandAttributes) {
    return;
  }
  if (elseCommandAttributes.name === 'if') {
    return elseCommandAttributes.ifSubject;
  }
  if (!elseCommandAttributes.skip && !Cypress._.isNil(elseCommandAttributes.subject)) {
    return elseCommandAttributes.subject;
  }
  if (elseCommandAttributes.prev) {
    return findMyIfSubject(elseCommandAttributes.prev.attributes);
  }
}

function getCurrentState() {
  return (cy as any).state('current');
}

// cy.if command
Cypress.Commands.add('if', { prevSubject: true }, function (subject, assertion?: any, assertionValue?: any) {
  const cmd = getCurrentState();
  // console.log('subjects', cy.state('subjects'))
  // keep the subject, if there is an "else" branch
  // it can look it up to use
  cmd.attributes.ifSubject = subject;

  // let's be friendly and if the user
  // wrote "if exists" just go with it
  if (assertion === 'exists') {
    assertion = 'exist';
  }

  let hasSubject = Boolean(subject);
  let assertionsPassed = true;

  const evaluateAssertion = () => {
    try {
      if (Cypress._.isFunction(assertion)) {
        const result = assertion(subject);
        if (Cypress._.isBoolean(result)) {
          // function was a predicate
          if (!result) {
            throw new Error('Predicate function failed');
          }
        }
      } else if (assertion.startsWith('not') || assertion.startsWith('have')) {
        const parts = assertion.split('.');
        let assertionReduced = expect(subject).to;
        parts.forEach((assertionPart: any, k: any) => {
          if (k === parts.length - 1 && typeof assertionValue !== 'undefined') {
            assertionReduced = assertionReduced[assertionPart](assertionValue);
          } else {
            assertionReduced = assertionReduced[assertionPart];
          }
        });
      } else {
        if (typeof assertionValue !== 'undefined') {
          expect(subject).to.be[assertion](assertionValue);
        } else {
          expect(subject).to.be[assertion];
        }
      }
    } catch (e: any) {
      console.error(e);
      assertionsPassed = false;
      if (e.message.includes('Invalid Chai property')) {
        throw e;
      }
    }
  };

  // check if the previous command was cy.task
  // and it has failed and it was expected
  if (
    assertion === 'failed' &&
    Cypress._.get(cmd, 'attributes.prev.attributes.name') === 'task' &&
    Cypress._.isError(Cypress._.get(cmd, 'attributes.prev.attributes.error'))
  ) {
    // set the subject and the assertions to take the IF branch
    hasSubject = <any>Cypress._.get(cmd, 'attributes.prev.attributes.error');
  } else {
    if (subject === null) {
      if (assertion === 'null') {
        hasSubject = true;
        assertionsPassed = true;
      } else if (assertion === 'not.null') {
        hasSubject = true;
        assertionsPassed = false;
      }
    } else if (hasSubject && assertion) {
      evaluateAssertion();
    } else if (subject === undefined && assertion) {
      evaluateAssertion();
      hasSubject = true;
    }
  }

  const chainerId = cmd.attributes.chainerId;
  if (!chainerId) {
    throw new Error('Command is missing chainer id');
  }

  if (!hasSubject || !assertionsPassed) {
    let nextCommand = cmd.attributes.next;
    while (nextCommand && nextCommand.attributes.chainerId === chainerId) {
      // cy.log(`**skipping ${cmd.attributes.next.attributes.name}**`)
      if (nextCommand.attributes.name === 'else') {
        nextCommand = null;
      } else {
        skipCommand(nextCommand);

        nextCommand = nextCommand.attributes.next;
        if (nextCommand && nextCommand.attributes.name === 'else') {
          nextCommand = null;
        }
      }
    }

    if (subject) {
      cy.wrap(subject, { log: false });
    }
    return;
  } else {
    // skip possible "else" branch
    let nextCommand = cmd.attributes.next;
    while (nextCommand && nextCommand.attributes.chainerId === chainerId) {
      if (nextCommand.attributes.name === 'else') {
        // found the "else" command, start skipping
        skipRestOfTheChain(nextCommand, chainerId);
        nextCommand = null;
      } else {
        nextCommand = nextCommand.attributes.next;
      }
    }
  }
  return subject;
});

Cypress.Commands.add('else', { prevSubject: true }, subject => {
  if (typeof subject === 'undefined') {
    // find the subject from the "if()" before
    subject = findMyIfSubject((cy as any).state('current').attributes);
  }
  if (subject) {
    cy.wrap(subject, { log: false });
  }
});

Cypress.Commands.add('finally', { prevSubject: true }, subject => {
  // notice: cy.log yields "null" 🤯
  // https://github.com/cypress-io/cypress/issues/23400
  if (typeof subject === 'undefined' || subject === null) {
    // find the subject from the "if()" before
    const currentCommand = (cy as any).state('current').attributes;
    subject = findMyIfSubject(currentCommand);
  }
  if (subject) {
    cy.wrap(subject, { log: false });
  }
});

Cypress.Commands.overwriteQuery('get', function (originalFn, selector, options) {
  // can we see the next command already?
  const cmd = getCurrentState();
  const innerFn = originalFn.call(this, selector, options);

  if (isIfCommand(cmd.attributes.next)) {
    // disable the built-in assertion
    return subject => {
      const res = innerFn(subject);
      if (res.length) {
        return res;
      }
    };
  }
  return subject => innerFn(subject);
});

Cypress.Commands.overwriteQuery('contains', function (originalFn, filter, text, options) {
  const cmd = getCurrentState();
  const innerFn = originalFn.call(this, filter, text, options);

  if (isIfCommand(cmd.attributes.next)) {
    // disable the built-in assertion
    return subject => {
      const res = innerFn(subject);
      if (res.length) {
        return res;
      }
    };
  }

  return subject => innerFn(subject);
});

Cypress.Commands.overwriteQuery('find', function (originalFn, selector, options) {
  const cmd = getCurrentState();
  const innerFn = originalFn.call(this, selector, options);

  if (isIfCommand(cmd.attributes.next)) {
    // disable the built-in assertion
    return subject => {
      const res = innerFn(subject);
      if (res.length) {
        return res;
      }
    };
  }

  return subject => innerFn(subject);
});

Cypress.Commands.overwrite('task', function (originalFn, args, options) {
  const cmd = getCurrentState();
  if (cmd) {
    const next = cmd.attributes.next;

    if (next && next.attributes.name === 'if') {
      // disable the built-in assertion
      return originalFn(args, options).then(
        (taskResult: any) => {
          return taskResult;
        },
        (error: any) => {
          console.log('task error', error);
          cmd.attributes.error = error;
        }
      );
    }
  }

  return originalFn(args, options);
});

Cypress.Commands.add('raise', x => {
  if (Cypress._.isError(x)) {
    throw x;
  }
  const e = new Error(String(x) + '\n' + 'cypress-if tip: pass an error instance to have correct stack');
  throw e;
});
`

We use cypress-if in quite a few tests (simple and also complex ones) and they're all running again with this changes.

Have fun with it!

**Comment by FMuellerBK** [comment]
Hey guys, 
I could get to run for Cypress 12.17.1 and Angular 16.1.5.
All your tests are passing, all of our tests too (from simple to complex ones).

I already created a branch locally, but I'm not allowed to push it.
Can you add me to the contributers, so I can create a PR for this?

Many thanks in advance!

**Comment by appdirectorsantosh** [comment]
> FMuellerBK

I think, you should be able to raise a PR after creating fork like below example-
https://github.com/bahmutov/cypress-if/pull/19

**Comment by FMuellerBK** [comment]
> > FMuellerBK
> 
> I think, you should be able to raise a PR after creating fork like below example- #19

Yes, you're right. Just create a PR from a fork.
Thanks for the help, I'm still not familiar with github :D
