### ISSUE TITLE
Upgraded to Cypress 12.17.4 and Cypress-if started throwing error even before the suite started

### ISSUE THREAD

**Issue by KRajeshBabu** [bahmutov/cypress-if#70]
Here is the error message from Cypress runner
`The following error originated from your test code, not from Cypress.`
`Cannot overwite the get query. Queries can only be overwritten with Cypress.Commands.overwriteQuery().`
`When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.`
`Cypress could not associate this error to any specific test.`
`node_modules/cypress-if/src/index.js:230:1`

![image](https://github.com/bahmutov/cypress-if/assets/17311379/f582bfc5-afa3-47d9-b766-0d83299d1ca3)

**Comment by bahmutov** [comment]
Are you using the latest version of cypress-if plug-in?Sent from my iPhoneOn Aug 23, 2023, at 12:57, Ragova ***@***.***> wrote:﻿
Here is the error message from Cypress runner
The following error originated from your test code, not from Cypress.
Cannot overwite the get query. Queries can only be overwritten with Cypress.Commands.overwriteQuery().
When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.
Cypress could not associate this error to any specific test.
node_modules/cypress-if/src/index.js:230:1

**Comment by KRajeshBabu** [comment]
Mine is "1.10.4" and latest is "1.10.5". 
Once I did upgrade to latest, it did worked fine. 
Sorry for the trouble.
